[package]
name = "auth-webapp"
version = "0.1.0"
edition = "2021"

[dependencies]
rocket = "0.5.0-rc.2"
fred = "5.1.0"
tokio = "1.20.1"
eyre = "0.6.8"
sha2 = "0.10.2"
base64 = "0.13.0"
dotenv = "0.15.0"

rocket_dyn_templates = { version = "0.1.0-rc.2", features = ["tera"]}